<?php
    define('THINK_PATH','./App/ThinkPHP/');
    //define('RUNTIME_ALLINONE',1);
    define('APP_NAME','App');
    define('APP_PATH','./App/');
    define('APP_DEBUG',0);
    define('APP_PUBLIC_PATH','../Public');
    require(THINK_PATH.'/ThinkPHP.php');
?>
